COMMENTS TABLE
CREATE TABLE COMMENTS(
COMMENT_ID INT PRIMARY KEY,
DESCRIPTION VARCHAR (255),
POSTED DATE,
USERID INT  FOREIGN KEY REFERENCES USERDATA(USER_ID),
POSTID INT  FOREIGN KEY REFERENCES POSTS(POST_ID))