CREATE TABLE USERDATA
(USER_ID INT PRIMARY KEY NOT NULL,
USERNAME VARCHAR (90) UNIQUE NOT NULL,
FIRSTNAME VARCHAR (100) NOT NULL,
LASTNAME VARCHAR (100)NOT NULL,
EMAIL VARCHAR(100) UNIQUE NOT NULL,
PASSWORD VARCHAR(70)NOT NULL,
GENDER VARCHAR (10) NOT NULL CHECK (GENDER IN ('Female','Male')) )